name: Azure Static WebSite CI/CD
run-name: "Deploy React app"
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - develop

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Set variables
        id: setvars
        run: |
          if [[ "${{ github.base_ref }}" == "develop" || "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo ENV_NAME="dev" >> $GITHUB_ENV
          fi

      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          
      - name: Configure Azure Credentials
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ARM_CREDENTIALS }}

      - name: 'Run az commands'
        run: |
          az account show
          az account set --subscription ${{ env.ARM_SUBSCRIPTION_ID }}
          az configure --defaults location=francecentral

      - name: 'Run build'
        shell: bash
        run: |
          echo "NodeJS Version:"
          node --version
          corepack enable
          corepack pnpm install
          corepack pnpm build
          rm -rf ./node_modules/* && rm -rf ./.vite/cache

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
              az storage blob upload-batch --account-name emat${ENV_NAME}frontendapp --overwrite true --auth-mode key -d '$web' -s ./dist/

      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          inlineScript: |
              az cdn endpoint purge --content-paths  "/*" --profile-name "emat-${ENV_NAME}-cdn-profile" --name "emat-${ENV_NAME}-cdn-endpoint" --resource-group "rg-TEPARAZRLD-app-emat-${ENV_NAME}"
  
      - name: logout
        run: |
              az logout
        if: always()